name       : engrampa
version    : 1.20.1
release    : 9
source     :
    - https://pub.mate-desktop.org/releases/1.20/engrampa-1.20.1.tar.xz : ce7013b40e6102aa4076009fa9bd09f8c0c3a951f484fb87380c4625a992e926
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Archive manager for the MATE Desktop
description: |
    Archive manager for the MATE Desktop
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcaja-extension)
    - pkgconfig(sm)
    - itstool
setup      : |
    %configure --enable-magic --disable-static
build      : |
    %make
install    : |
    %make_install
