name       : engrampa
version    : 1.20.0
release    : 7
source     :
    - https://pub.mate-desktop.org/releases/1.20/engrampa-1.20.0.tar.xz : d5daac72a67a5e5b3d317f0031cc59e63c89c9b5fcc689932e192812e22860de
license    : GPL-2.0
component  : desktop.mate
summary    : Archive manager for the MATE Desktop
description: |
    Archive manager for the MATE Desktop
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcaja-extension)
    - pkgconfig(sm)
    - itstool
setup      : |
    %configure --enable-magic --disable-static
build      : |
    %make
install    : |
    %make_install
