name       : engrampa
version    : 1.24.2
release    : 22
source     :
    - https://github.com/mate-desktop/engrampa/releases/download/v1.24.2/engrampa-1.24.2.tar.xz : ee280d288c974732ec7bc2d1c3e18fa563b33a30f3e4cb3e976ebc71be6c4674
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Archive manager for the MATE Desktop
description: |
    Engrampa is an application for creating and viewing archives files, such as zip, xv, bzip2, cab, rar and other compress formats.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcaja-extension)
    - pkgconfig(sm)
    - itstool
setup      : |
    %configure --disable-static \
        --disable-packagekit \
        --enable-magic
build      : |
    %make
install    : |
    %make_install
