name       : engrampa
version    : 1.22.1
release    : 13
source     :
    - https://github.com/mate-desktop/engrampa/archive/v1.22.1.tar.gz : e7573e0b96034312be468726fab368e20e87f58b7ec8e037d6cfe085682819ea
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Archive manager for the MATE Desktop
description: |
    Engrampa is an application for creating and viewing archives files, such as zip, xv, bzip2, cab, rar and other compress formats.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcaja-extension)
    - pkgconfig(sm)
    - itstool
    - mate-common
    - yelp-tools
setup      : |
    %autogen --disable-static \
        --disable-packagekit \
        --enable-magic
build      : |
    %make
install    : |
    %make_install
