name       : engrampa
version    : 1.20.2
release    : 10
source     :
    - https://pub.mate-desktop.org/releases/1.20/engrampa-1.20.2.tar.xz : 5bb8d1467824a770b2bdfe4e8b3d0a1b0e2e6482859482ebb9863fe5da29493a
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Archive manager for the MATE Desktop
description: |
    Archive manager for the MATE Desktop
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcaja-extension)
    - pkgconfig(sm)
    - itstool
setup      : |
    %configure --enable-magic --disable-static
build      : |
    %make
install    : |
    %make_install
