name       : engrampa
version    : 1.22.0
release    : 11
source     :
    - https://github.com/mate-desktop//engrampa/archive/v1.22.0.tar.gz : bf8638775cfa5e7b017cdeeef41e2a4260b3d71de46b1a7c0fd0785020acb922
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Archive manager for the MATE Desktop
description: |
    Engrampa is an application for creating and viewing archives files, such as zip, xv, bzip2, cab, rar and other compress formats.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcaja-extension)
    - pkgconfig(sm)
    - itstool
    - mate-common
    - yelp-tools
setup      : |
    %autogen --disable-static \
        --disable-packagekit \
        --enable-magic
build      : |
    %make
install    : |
    %make_install
