name       : engrampa
version    : 1.22.3
release    : 16
source     :
    - https://pub.mate-desktop.org/releases/1.22/engrampa-1.22.3.tar.xz : d66c3b1721f178be78f0e28b2fcf33293fc419fe966150769723a8901f0ef69e
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Archive manager for the MATE Desktop
description: |
    Engrampa is an application for creating and viewing archives files, such as zip, xv, bzip2, cab, rar and other compress formats.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcaja-extension)
    - pkgconfig(sm)
    - itstool
    - mate-common
    - yelp-tools
setup      : |
    %autogen --disable-static \
        --disable-packagekit \
        --enable-magic
build      : |
    %make
install    : |
    %make_install
