name       : engrampa
version    : 1.27.0
release    : 25
source     :
    - https://github.com/mate-desktop/engrampa/releases/download/v1.27.0/engrampa-1.27.0.tar.xz : 1bb757d72d03787f2475d85e0741b3cd0f745e956fa55bc66c7921325c50130f
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Archive manager for the MATE Desktop
description: |
    Engrampa is an application for creating and viewing archives files, such as zip, xv, bzip2, cab, rar and other compress formats.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcaja-extension)
    - pkgconfig(sm)
    - itstool
setup      : |
    %configure --disable-static \
        --disable-packagekit \
        --enable-magic
build      : |
    %make
install    : |
    %make_install
